### ISSUE TITLE
add LICENSE

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/stride#2]
Please add the license under which the code has been obtained. Also make clear the source.

**Comment by orbeckst** [comment]
oops, saw LICENSE file, just GitHub didn't recognize it.

**Comment by orbeckst** [comment]
Note that this is *not a free license* because it places lots of restrictions on use and requires authors to report bugs to authors.

I am sure that it is not compatible with GPL.

**Comment by orbeckst** [comment]
I would actually suggest to ditch the STRIDE code for those reasons. Either reimplement from the paper or use DSSP (which is free/libre).

**Comment by richardjgowers** [comment]
@orbeckst yeah I wasn't sure, but rereading it I'm not sure we can use this freely.  Might have to ditch this idea

**Comment by kain88-de** [comment]
@orbeckst do you know where to find the dssp source? I only see find executables on their websites.

**Comment by orbeckst** [comment]
It was hard to find the last time I looked. 

To find ftp://ftp.cmbi.ru.nl/pub/molbio/software/dssp-2/ <ftp://ftp.cmbi.ru.nl/pub/molbio/software/dssp-2/> where there are source code tarballs under the Boost licence I started from the DSSP Debian package page https://tracker.debian.org/pkg/dssp <https://tracker.debian.org/pkg/dssp>.

**Comment by richardjgowers** [comment]
@kain88-de https://github.com/MDAnalysis/dssp
